replicaCount: 2
image:
  repository: nginx
  tag: "latest"
service:
  type: ClusterIP
  port: 80
serviceAccount:
  create: true
  annotations: {}
  automount: true
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
