apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-demo.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "nginx-demo.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
